linux-mbp 5.14.3 -> 5.16.1, wifi-firmware otp naming scheme and selection
t2linux/nixos-overlay pull request #3
Opened 2022-01-17 12:07 UTC by Redecorating

Besides a few changes to make the existing patches apply on newer
kernels:

Includes asahilinux's wifi patches, which make linux select firmware as
macos does. This means the naming scheme for firmware has been changed,
and you no longer need to specify your model and firmware files
manually.

The 4010 patch makes fn+1 = f1, etc. This is useful when the touchbar
doesn't work.

0101 patch fixes nvram writes by using efiruntime v1.10 instead of
v2.40, which means linux won't use the call that caused the crashes

3007 adds iMacPro to a list of model types in applesmc.

A few patches (2001, 6001, 7001) have been updated to versions that have
recently been submitted upstream.

9001-2 are now in upstream stable.

Adding iommu=pt to kernel arguments fixes issues with audio input when
using intel_iommu=on (audio is disabled by the other kernel argument, but if someone were to enable
it then they may not realise that iommu=pt is required).

2022-01-17 12:35 UTC, mikroskeem requested changes

2022-01-17 12:35 UTC, mikroskeem commented on packages/firmware/apple-wifi-firmware/default.nix
> +  buildInputs = [ python310 ];
Should be `nativeBuildInputs`

2022-01-17 12:35 UTC, mikroskeem commented on packages/firmware/apple-wifi-firmware/default.nix
> +  asahi_installer = fetchFromGitHub {
I believe this could be extracted into its own derivation as a standalone tool

2022-01-17 12:35 UTC, mikroskeem commented on packages/firmware/apple-wifi-firmware/default.nix
> +    sha256 = "109fybj7mqkdmlxv4vwp89zhf8b8aw4a3dgdwmwsla1lid7xd2i3";
Could use SRI-style hash here as well

2022-01-17 12:35 UTC, mikroskeem commented on packages/firmware/apple-wifi-firmware/default.nix
> +  buildInputs = [ python310 ];
Difference between those two is that if you'll try to build this derivation on e.g macOS directly, then it'd use macOS build for python (in other words "native"). While it's unlikely at the moment that it's buildable on macOS, it'd just be more correct.

2022-01-17 13:03 UTC, Redecorating commented on packages/firmware/apple-wifi-firmware/default.nix
>        runHook postInstall
Do you mean before this pr is merged (if it does get merged) or after? If you mean before, would me changing it to nativebuildinput and changing that hash cause issues with the git history for you (force pushing to squash the fixups into the original commit might cause issues). In any case, I won't have time to make those changes until tomorrow.

2022-01-17 13:06 UTC, mikroskeem commented on packages/firmware/apple-wifi-firmware/default.nix
>        runHook postInstall
I can push into this PR I believe. Feel free to force push.

> In any case, I won't have time to make those changes until tomorrow.

No worries, will do it by myself if I have time

2022-12-04 09:34 UTC, closed without merging

2022-12-04 09:34 UTC, Redecorating commented
I forgot this was still here but we're using the other repo so closing this pr